rubocop:
  config_file: .rubocop.yml
  version: 0.63.0
coffeescript:
  config_file: coffeescript.json
scss:
  config_file: .scss-lint.yml
javascript:
  ignore_file: .js-ignore
eslint:
  enabled: true
